ArangaliITELEC1C/Models/ErrorViewModel.cs
namespace ArangaliITELEC1C.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ArangaliITELEC1C/Models/Instructor.cs
namespace ArangaliITELEC1C.Models;

public enum Rank
{ 
    Instructor, AsstistantProfessor, Professor, AssociateProfessor,
}

public class Instructor
{
    public int Id { get; set; }
    public string InstructorFirstName { get; set; }
    public string InstructorLastName { get; set; }
    public bool InstructorIsTenured { get; set; }
    public DateTime DateHired { get; set; }
    public Rank Rank { get; set; }
}

ArangaliITELEC1C/Models/Student.cs
namespace ArangaliITELEC1C.Models;

public enum Course
{
    BSIT, BSCS, BSIS, OTHER
}

public class Student
{
    public int StudentId { get; set; }
    public string StudentFirstName { get; set; }
    public string StudentLastName { get; set; }
    public DateTime AdmissionDate { get; set; }
    public Course Course { get; set; }
    public string Email { get; set; }
    public double GPA { get; set; }
}

ArangaliITELEC1C/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ArangaliITELEC1C.Models;

namespace ArangaliITELEC1C.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ArangaliITELEC1C/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using ArangaliITELEC1C.Models;
using ArangaliITELEC1C.Services;

namespace ArangaliITELEC1C.Controllers;

    public class InstructorController : Controller
    {
        private readonly IMyFakeDataService _dummyData;

       public InstructorController(IMyFakeDataService dummyData)
    {
        _dummyData = dummyData;
    }

    public IActionResult Index()
        {
        return View(_dummyData.InstructorList);
    }

    public IActionResult ShowDetail(int id)
    {
        //Search for the Instructor whose id matches the given id
        Instructor? instructor = _dummyData.InstructorList.FirstOrDefault(st => st.Id == id);

        if (instructor != null)//was an instructor found?
            return View(instructor);

        return NotFound();
    }

    [HttpGet]
    public IActionResult AddInstructor()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddInstructor(Instructor newInstructor)
    {
        _dummyData.InstructorList.Add(newInstructor);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult UpdateInstructor(int id)
    {
        Instructor? instructor = _dummyData.InstructorList.FirstOrDefault(st => st.Id == id);

        if (instructor != null)//was an instructor found?
            return View(instructor);

        return NotFound();
    }

    [HttpPost]
    public IActionResult UpdateStudent(Instructor instructorChanges)
    {
        Instructor? instructor= _dummyData.InstructorList.FirstOrDefault(st => st.Id == instructorChanges.Id);

        if (instructor != null)
        {
            instructor.InstructorFirstName = instructorChanges.InstructorFirstName;
            instructor.InstructorLastName = instructorChanges.InstructorLastName;
            instructor.InstructorIsTenured = instructorChanges.InstructorIsTenured;
            instructor.Rank = instructorChanges.Rank;
            instructor.DateHired = instructorChanges.DateHired;
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {

        Instructor? instructor = _dummyData.InstructorList.FirstOrDefault(st => st.Id == id);

        if (instructor != null)//was an instructor found?
            return View(instructor);

        return NotFound();
    }

    [HttpPost]
    public IActionResult Delete(Instructor newInstructor)
    {
        Instructor? instructor = _dummyData.InstructorList.FirstOrDefault(st => st.Id == newInstructor.Id);

        if (instructor != null)
            _dummyData.InstructorList.Remove(instructor);
        return RedirectToAction("Index");
    }
}

ArangaliITELEC1C/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using ArangaliITELEC1C.Models;
using ArangaliITELEC1C.Services;

namespace ArangaliITELEC1C.Controllers
{
    public class StudentController : Controller
    {
        private readonly IMyFakeDataService _dummyData;

            public StudentController(IMyFakeDataService dummyData)
        {
            _dummyData = dummyData;
        }



        public IActionResult Index()
        {
            return View(_dummyData.StudentList);
        }

        public IActionResult ShowDetail(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Student newStudent)
        {
            _dummyData.StudentList.Add(newStudent);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult UpdateStudent(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student studentChanges)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == studentChanges.StudentId);

            if (student != null)
            {
                student.StudentFirstName = studentChanges.StudentFirstName;
                student.StudentLastName = studentChanges.StudentLastName;
                student.Email = studentChanges.Email;
                student.Course = studentChanges.Course;
                student.GPA = studentChanges.GPA;
                student.AdmissionDate = studentChanges.AdmissionDate;
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == id);

            if (student != null)
                return View(student);

            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(Student newStudent)
        {
            Student? student = _dummyData.StudentList.FirstOrDefault(st => st.StudentId == newStudent.StudentId);

            if (student != null)
                _dummyData.StudentList.Remove(student);
            return RedirectToAction("Index");
        }
    }
}

ArangaliITELEC1C/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ArangaliITELEC1C/Views/Instructor/AddInstructor.cshtml
@model Instructor;

<form asp-action="AddInstructor" asp-controller="Instructor" method="post">
    <div class="form-group">
        <label asp-for="InstructorFirstName">First Name</label>
        <input asp-for="InstructorFirstName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="InstructorLastName">Last Name</label>
        <input asp-for="InstructorLastName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="InstructorIsTenured">InstructorIsTenured</label>
        <select asp-for="@Model.InstructorIsTenured" class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="DateHired">AdmussionDate</label>
        <input asp-for="DateHired" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Rank">Rank</label>
        <input asp-for="Rank" class="form-control"></>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>

ArangaliITELEC1C/Views/Instructor/Delete.cshtml
@model Instructor;

<form asp-action="Delete" asp-controller="Instructor" method="post">
    <h1> Are you sure you want to delete? </h1>
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control" readonly>
    </div>
    <div class="form-group">
        <label asp-for="InstructorFirstName">First Name</label>
        <input asp-for="InstructorFirstName" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="InstructorLastName">Last Name</label>
        <input asp-for="InstructorLastName" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="InstructorIsTenured">Tenured</label>
        <input asp-for="@Model.InstructorIsTenured" readonly></input>
    </div>

    <div class="form-group">
        <label asp-for="DateHired">AdmussionDate</label>
        <input asp-for="DateHired" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="Rank">Rank</label>
        <input asp-for="Rank" class="form-control" readonly></>
    </div>
    <button type="submit" class="btn btn-primary">Delete</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>

ArangaliITELEC1C/Views/Instructor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Instructor>
<h1>Instructor List</h1>

<table class="table table-dark">
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>IsTenured</th>
        <th>Rank</th>
        <th>Hiring Date</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>

    @foreach (var Instructor in Model)
    {
        <tr>
            <td>@Instructor.Id</td>
            <td>@Instructor.InstructorFirstName</td>
            <td>@Instructor.InstructorLastName</td>
            <td>@Instructor.InstructorIsTenured</td>
            <td>@Instructor.Rank</td>
            <td>@Instructor.DateHired</td>
            <td><a asp-action="ShowDetail" asp-route-id="@Instructor.Id" class="btn btn-primary">Show Details</a></td>
            <td><a asp-action="UpdateInstructor" asp-route-id="@Instructor.Id" class="btn btn-primary">Update</a></td>
            <td><a asp-action="Delete" asp-route-id="@Instructor.Id" class="btn btn-danger">Delete</a></td>
        </tr>
    }
</table>
<br />
<a asp-action="AddInstructor" class="btn btn-primary">Add Instructor</a>

ArangaliITELEC1C/Views/Instructor/ShowDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Instructor;
<h1>Instructor Details</h1>

<table class="table table-dark">
    <tr>
        <th>ID:</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Last Name:</th>
        <td>@Model.InstructorLastName</td>
    </tr>
    <tr>
        <th>First Name:</th>
        <td>@Model.InstructorFirstName</td>
    </tr>
    <tr>
        <th>IsTenured:</th>
        <td>@Model.InstructorIsTenured</td>
    </tr>
    <tr>
        <th>Rank:</th>
        <td>@Model.Rank</td>
    </tr>
    <tr>
        <th>Hiring Date:</th>
        <td>@Model.DateHired</td>
    </tr>
</table>

ArangaliITELEC1C/Views/Instructor/UpdateInstructor.cshtml
@model Instructor;

<form asp-action="AddInstructor" asp-controller="Instructor" method="post">
    <div class="form-group">
        <label asp-for="InstructorFirstName">First Name</label>
        <input asp-for="InstructorFirstName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="InstructorLastName">Last Name</label>
        <input asp-for="InstructorLastName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="InstructorIsTenured">Tenured</label>
        <input asp-for="@Model.InstructorIsTenured"></input>
    </div>

    <div class="form-group">
        <label asp-for="DateHired">AdmussionDate</label>
        <input asp-for="DateHired" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Rank">Rank</label>
        <input asp-for="Rank" class="form-control"></>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>

ArangaliITELEC1C/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArangaliITELEC1C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArangaliITELEC1C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ArangaliITELEC1C</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ArangaliITELEC1C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ArangaliITELEC1C/Views/Student/AddStudent.cshtml
@model Student;

<form asp-action="AddStudent" asp-controller="Student" method="post">
    <div class="form-group">
        <label asp-for="StudentFirstName">First Name</label>
        <input asp-for="StudentFirstName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="StudentLastName">Last Name</label>
        <input asp-for="StudentLastName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input asp-for="GPA" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Course">Course</label>
        <select asp-for="Course" asp-items="@Html.GetEnumSelectList(typeof(Course))" class=" form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="AdmissionDate">AdmussionDate</label>
        <input asp-for="AdmissionDate" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control"></>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>

ArangaliITELEC1C/Views/Student/Delete.cshtml
@model Student;

<h1> Are you sure you want to delete? </h1>
<form asp-action="Delete" asp-controller="Student" method="post">
    <div class="form-group">
        <label asp-for="StudentId">Id</label>
        <input asp-for="StudentId" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="StudentFirstName">First Name</label>
        <input asp-for="StudentFirstName" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="StudentLastName">Last Name</label>
        <input asp-for="StudentLastName" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input asp-for="GPA" class="form-control" readonly />
    </div>

    <div class="form-group">
        <label asp-for="Course">Course</label>
        <select asp-for="Course" asp-items="@Html.GetEnumSelectList(typeof(Course))" class=" form-control" readonly></select>
    </div>

    <div class="form-group">
        <label asp-for="AdmissionDate">Admission Date</label>
        <input asp-for="AdmissionDate" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control" readonly></>
    </div>

    <button type="submit" class="btn btn-primary">Delete</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>

ArangaliITELEC1C/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<table class="table table-dark">
    <tr>
        <h1>Student List</h1>
    </tr>
    <tr>
        <th>Name</th>
        <th>Course</th>
        <th>Admission Date</th>
        <th>Email</th>
        <th>GPA</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>

    </tr>



    @foreach (var student in Model)
    {
        <tr>
            <td>@student.StudentLastName, @student.StudentFirstName</td>
            <td>@student.Course</td>
            <td>@student.AdmissionDate</td>
            <td>@student.Email</td>
            <td>@student.GPA</td>
            <td><a asp-action="ShowDetail" asp-route-id="@student.StudentId" class="btn btn-primary">Show Details</a></td>
            <td><a asp-action="UpdateStudent" asp-route-id="@student.StudentId" class="btn btn-primary">Update</a></td>
            <td><a asp-action="Delete" asp-route-id="@student.StudentId" class="btn btn-danger">Delete</a></td>
        </tr>
    }

</table><br />
        <a asp-action="AddStudent" class="btn btn-primary">Add Student</a>

ArangaliITELEC1C/Views/Student/ShowDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student;
<table class="table table-dark">
    <tr>
        <th>Id</th>
        <td>@Model.StudentId</td>
    </tr>

    <tr>
        <th>Last Name</th>
        <td>@Model.StudentLastName</td>
    </tr>

    <tr>
        <th>First Name</th>
        <td>@Model.StudentFirstName</td>
    </tr>

    <tr>
        <th>Course</th>
        <td>@Model.Course</td>
    </tr>

    <tr>
        <th>Email</th>
        <td>@Model.Email</td>
    </tr>

    <tr>
        <th>Admission Date</th>
        <td>@Model.AdmissionDate</td>
    </tr>

    <tr>
        <th>GPA</th>
        <td>@Model.GPA</td>
    </tr>
</table>

ArangaliITELEC1C/Views/Student/UpdateStudent.cshtml
@model Student;

    <h1> Update Details </h1>
<form asp-action="UpdateStudent" asp-controller="Student" method="post">
    <div class="form-group">
        <label asp-for="StudentFirstName">First Name</label>
        <input asp-for="StudentFirstName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="StudentLastName">Last Name</label>
        <input asp-for="StudentLastName" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="GPA">GPA</label>
        <input asp-for="GPA" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Course">Course</label>
        <select asp-for="Course" asp-items="@Html.GetEnumSelectList(typeof(Course))" class=" form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="AdmissionDate">AdmussionDate</label>
        <input asp-for="AdmissionDate" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control"></>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" onclick="history.back()" class="btn btn-secondary">Cancel</button>
</form>